carnet_addressBook_contact_lister:
    path:     /
    defaults: { _controller: carnetAddressBookBundle:Contact:lister }

carnet_addressBook_contact_ajouter:
    path:     /contact/ajouter
    defaults: { _controller: carnetAddressBookBundle:Contact:ajouter }

carnet_addressBook_societe_lister:
    path:     /societe/lister
    defaults: { _controller: carnetAddressBookBundle:Societe:lister }
    
carnet_addressBook_societe_details:
    path:     /societe/{id}
    defaults: { _controller: carnetAddressBookBundle:Societe:details }
    requirements:
        id: "[1-9][0-9]*"

carnet_addressBook_societe_ajouter:
    path:     /societe/ajouter
    defaults: { _controller: carnetAddressBookBundle:Societe:ajouter }

carnet_addressBook_groupe_lister:
    path:     /groupe/lister
    defaults: { _controller: carnetAddressBookBundle:Groupe:lister }
    
carnet_addressBook_groupe_details:
    path:     /groupe/{id}
    defaults: { _controller: carnetAddressBookBundle:Groupe:details }
    requirements:
        id: "[1-9][0-9]*"

carnet_addressBook_groupe_ajouter:
    path:     /groupe/ajouter
    defaults: { _controller: carnetAddressBookBundle:Groupe:ajouter }
