carnet_addressBook_contact_lister:
    path:     /
    defaults: { _controller: carnetAddressBookBundle:Contact:lister }

carnet_addressBook_contact_ajouter:
    path:     /ajouter
    defaults: { _controller: carnetAddressBookBundle:Contact:ajouter }

carnet_addressBook_societe_lister:
    path:     /lister
    defaults: { _controller: carnetAddressBookBundle:Societe:lister }

carnet_addressBook_societe_ajouter:
    path:     /ajouter
    defaults: { _controller: carnetAddressBookBundle:Societe:ajouter }

carnet_addressBook_groupe_lister:
    path:     /lister
    defaults: { _controller: carnetAddressBookBundle:Groupe:lister }

carnet_addressBook_groupe_ajouter:
    path:     /ajouter
    defaults: { _controller: carnetAddressBookBundle:Groupe:ajouter }
