parameters:
#    carnet_address_book.example.class: carnet\AddressBookBundle\Example

services:
#    carnet_address_book.example:
#        class: %carnet_address_book.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
